test_that("codes are correct", {
  expect_identical(clock_codes$january, 1L)
  expect_identical(clock_codes$february, 2L)
  expect_identical(clock_codes$march, 3L)
  expect_identical(clock_codes$april, 4L)
  expect_identical(clock_codes$may, 5L)
  expect_identical(clock_codes$june, 6L)
  expect_identical(clock_codes$july, 7L)
  expect_identical(clock_codes$august, 8L)
  expect_identical(clock_codes$september, 9L)
  expect_identical(clock_codes$october, 10L)
  expect_identical(clock_codes$november, 11L)
  expect_identical(clock_codes$december, 12L)

  expect_identical(clock_codes$sunday, 1L)
  expect_identical(clock_codes$monday, 2L)
  expect_identical(clock_codes$tuesday, 3L)
  expect_identical(clock_codes$wednesday, 4L)
  expect_identical(clock_codes$thursday, 5L)
  expect_identical(clock_codes$friday, 6L)
  expect_identical(clock_codes$saturday, 7L)

  expect_identical(clock_codes$iso$monday, 1L)
  expect_identical(clock_codes$iso$tuesday, 2L)
  expect_identical(clock_codes$iso$wednesday, 3L)
  expect_identical(clock_codes$iso$thursday, 4L)
  expect_identical(clock_codes$iso$friday, 5L)
  expect_identical(clock_codes$iso$saturday, 6L)
  expect_identical(clock_codes$iso$sunday, 7L)
})

test_that("can't add to environment or modify bindings", {
  expect_snapshot_error(clock_codes$new <- 1)
  expect_snapshot_error(clock_codes$friday <- 1)
})
