# Generated by cpp11: do not edit by hand

format_duration_cpp <- function(fields, precision_string) {
  .Call("_clock_format_duration_cpp", fields, precision_string, PACKAGE = "clock")
}

duration_helper_cpp <- function(n, precision_string) {
  .Call("_clock_duration_helper_cpp", n, precision_string, PACKAGE = "clock")
}

duration_cast_cpp <- function(fields, precision_from, precision_to) {
  .Call("_clock_duration_cast_cpp", fields, precision_from, precision_to, PACKAGE = "clock")
}

duration_plus_cpp <- function(x, y, precision_x, precision_y) {
  .Call("_clock_duration_plus_cpp", x, y, precision_x, precision_y, PACKAGE = "clock")
}

duration_minus_cpp <- function(x, y, precision_x, precision_y) {
  .Call("_clock_duration_minus_cpp", x, y, precision_x, precision_y, PACKAGE = "clock")
}

duration_common_precision_cpp <- function(x_precision, y_precision) {
  .Call("_clock_duration_common_precision_cpp", x_precision, y_precision, PACKAGE = "clock")
}

duration_has_common_precision_cpp <- function(x_precision, y_precision) {
  .Call("_clock_duration_has_common_precision_cpp", x_precision, y_precision, PACKAGE = "clock")
}

duration_floor_cpp <- function(fields, precision_from, precision_to) {
  .Call("_clock_duration_floor_cpp", fields, precision_from, precision_to, PACKAGE = "clock")
}

duration_ceil_cpp <- function(fields, precision_from, precision_to) {
  .Call("_clock_duration_ceil_cpp", fields, precision_from, precision_to, PACKAGE = "clock")
}

duration_round_cpp <- function(fields, precision_from, precision_to) {
  .Call("_clock_duration_round_cpp", fields, precision_from, precision_to, PACKAGE = "clock")
}

duration_unary_minus_cpp <- function(fields, precision_string) {
  .Call("_clock_duration_unary_minus_cpp", fields, precision_string, PACKAGE = "clock")
}

format_time_point_cpp <- function(fields, clock, format, precision_string, mon, mon_ab, day, day_ab, am_pm, decimal_mark) {
  .Call("_clock_format_time_point_cpp", fields, clock, format, precision_string, mon, mon_ab, day, day_ab, am_pm, decimal_mark, PACKAGE = "clock")
}

format_zoned_time_cpp <- function(fields, zone, abbreviate_zone, format, precision_string, mon, mon_ab, day, day_ab, am_pm, decimal_mark) {
  .Call("_clock_format_zoned_time_cpp", fields, zone, abbreviate_zone, format, precision_string, mon, mon_ab, day, day_ab, am_pm, decimal_mark, PACKAGE = "clock")
}

year_month_day_check_range_cpp <- function(x, component, arg) {
  invisible(.Call("_clock_year_month_day_check_range_cpp", x, component, arg, PACKAGE = "clock"))
}

collect_year_month_day_fields <- function(fields, precision_string) {
  .Call("_clock_collect_year_month_day_fields", fields, precision_string, PACKAGE = "clock")
}

format_year_month_day_cpp <- function(fields, precision_string) {
  .Call("_clock_format_year_month_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_detect_year_month_day_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_detect_year_month_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_any_year_month_day_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_any_year_month_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_count_year_month_day_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_count_year_month_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_resolve_year_month_day_cpp <- function(fields, precision_string, invalid_string) {
  .Call("_clock_invalid_resolve_year_month_day_cpp", fields, precision_string, invalid_string, PACKAGE = "clock")
}

set_field_year_month_day_cpp <- function(fields, value, precision_fields, precision_value) {
  .Call("_clock_set_field_year_month_day_cpp", fields, value, precision_fields, precision_value, PACKAGE = "clock")
}

set_field_year_month_day_last_cpp <- function(fields, precision_fields) {
  .Call("_clock_set_field_year_month_day_last_cpp", fields, precision_fields, PACKAGE = "clock")
}

year_month_day_plus_duration_cpp <- function(fields, fields_n, precision_fields, precision_n) {
  .Call("_clock_year_month_day_plus_duration_cpp", fields, fields_n, precision_fields, precision_n, PACKAGE = "clock")
}

as_sys_time_year_month_day_cpp <- function(fields, precision_string) {
  .Call("_clock_as_sys_time_year_month_day_cpp", fields, precision_string, PACKAGE = "clock")
}

as_year_month_day_from_sys_time_cpp <- function(fields, precision_string) {
  .Call("_clock_as_year_month_day_from_sys_time_cpp", fields, precision_string, PACKAGE = "clock")
}

year_month_day_minus_year_month_day_cpp <- function(x, y, precision_string) {
  .Call("_clock_year_month_day_minus_year_month_day_cpp", x, y, precision_string, PACKAGE = "clock")
}

year_month_weekday_check_range_cpp <- function(x, component, arg) {
  invisible(.Call("_clock_year_month_weekday_check_range_cpp", x, component, arg, PACKAGE = "clock"))
}

collect_year_month_weekday_fields <- function(fields, precision_string) {
  .Call("_clock_collect_year_month_weekday_fields", fields, precision_string, PACKAGE = "clock")
}

format_year_month_weekday_cpp <- function(fields, precision_string) {
  .Call("_clock_format_year_month_weekday_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_detect_year_month_weekday_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_detect_year_month_weekday_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_any_year_month_weekday_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_any_year_month_weekday_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_count_year_month_weekday_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_count_year_month_weekday_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_resolve_year_month_weekday_cpp <- function(fields, precision_string, invalid_string) {
  .Call("_clock_invalid_resolve_year_month_weekday_cpp", fields, precision_string, invalid_string, PACKAGE = "clock")
}

set_field_year_month_weekday_cpp <- function(fields, value, precision_fields, component) {
  .Call("_clock_set_field_year_month_weekday_cpp", fields, value, precision_fields, component, PACKAGE = "clock")
}

set_field_year_month_weekday_last_cpp <- function(fields, precision_fields) {
  .Call("_clock_set_field_year_month_weekday_last_cpp", fields, precision_fields, PACKAGE = "clock")
}

year_month_weekday_plus_duration_cpp <- function(fields, fields_n, precision_fields, precision_n) {
  .Call("_clock_year_month_weekday_plus_duration_cpp", fields, fields_n, precision_fields, precision_n, PACKAGE = "clock")
}

as_sys_time_year_month_weekday_cpp <- function(fields, precision_string) {
  .Call("_clock_as_sys_time_year_month_weekday_cpp", fields, precision_string, PACKAGE = "clock")
}

as_year_month_weekday_from_sys_time_cpp <- function(fields, precision_string) {
  .Call("_clock_as_year_month_weekday_from_sys_time_cpp", fields, precision_string, PACKAGE = "clock")
}

year_month_weekday_minus_year_month_weekday_cpp <- function(x, y, precision_string) {
  .Call("_clock_year_month_weekday_minus_year_month_weekday_cpp", x, y, precision_string, PACKAGE = "clock")
}

clock_set_install <- function(path) {
  invisible(.Call("_clock_clock_set_install", path, PACKAGE = "clock"))
}

iso_year_week_day_check_range_cpp <- function(x, component, arg) {
  invisible(.Call("_clock_iso_year_week_day_check_range_cpp", x, component, arg, PACKAGE = "clock"))
}

collect_iso_year_week_day_fields <- function(fields, precision_string) {
  .Call("_clock_collect_iso_year_week_day_fields", fields, precision_string, PACKAGE = "clock")
}

format_iso_year_week_day_cpp <- function(fields, precision_string) {
  .Call("_clock_format_iso_year_week_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_detect_iso_year_week_day_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_detect_iso_year_week_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_any_iso_year_week_day_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_any_iso_year_week_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_count_iso_year_week_day_cpp <- function(fields, precision_string) {
  .Call("_clock_invalid_count_iso_year_week_day_cpp", fields, precision_string, PACKAGE = "clock")
}

invalid_resolve_iso_year_week_day_cpp <- function(fields, precision_string, invalid_string) {
  .Call("_clock_invalid_resolve_iso_year_week_day_cpp", fields, precision_string, invalid_string, PACKAGE = "clock")
}

set_field_iso_year_week_day_cpp <- function(fields, value, precision_fields, precision_value) {
  .Call("_clock_set_field_iso_year_week_day_cpp", fields, value, precision_fields, precision_value, PACKAGE = "clock")
}

set_field_iso_year_week_day_last_cpp <- function(fields, precision_fields) {
  .Call("_clock_set_field_iso_year_week_day_last_cpp", fields, precision_fields, PACKAGE = "clock")
}

iso_year_week_day_plus_duration_cpp <- function(fields, fields_n, precision_fields, precision_n) {
  .Call("_clock_iso_year_week_day_plus_duration_cpp", fields, fields_n, precision_fields, precision_n, PACKAGE = "clock")
}

as_sys_time_iso_year_week_day_cpp <- function(fields, precision_string) {
  .Call("_clock_as_sys_time_iso_year_week_day_cpp", fields, precision_string, PACKAGE = "clock")
}

as_iso_year_week_day_from_sys_time_cpp <- function(fields, precision_string) {
  .Call("_clock_as_iso_year_week_day_from_sys_time_cpp", fields, precision_string, PACKAGE = "clock")
}

iso_year_week_day_minus_iso_year_week_day_cpp <- function(x, y, precision_string) {
  .Call("_clock_iso_year_week_day_minus_iso_year_week_day_cpp", x, y, precision_string, PACKAGE = "clock")
}

year_quarter_day_check_range_cpp <- function(x, component, arg) {
  invisible(.Call("_clock_year_quarter_day_check_range_cpp", x, component, arg, PACKAGE = "clock"))
}

collect_year_quarter_day_fields <- function(fields, precision_string, start) {
  .Call("_clock_collect_year_quarter_day_fields", fields, precision_string, start, PACKAGE = "clock")
}

format_year_quarter_day_cpp <- function(fields, precision_string, start) {
  .Call("_clock_format_year_quarter_day_cpp", fields, precision_string, start, PACKAGE = "clock")
}

invalid_detect_year_quarter_day_cpp <- function(fields, precision_string, start) {
  .Call("_clock_invalid_detect_year_quarter_day_cpp", fields, precision_string, start, PACKAGE = "clock")
}

invalid_any_year_quarter_day_cpp <- function(fields, precision_string, start) {
  .Call("_clock_invalid_any_year_quarter_day_cpp", fields, precision_string, start, PACKAGE = "clock")
}

invalid_count_year_quarter_day_cpp <- function(fields, precision_string, start) {
  .Call("_clock_invalid_count_year_quarter_day_cpp", fields, precision_string, start, PACKAGE = "clock")
}

invalid_resolve_year_quarter_day_cpp <- function(fields, precision_string, start, invalid_string) {
  .Call("_clock_invalid_resolve_year_quarter_day_cpp", fields, precision_string, start, invalid_string, PACKAGE = "clock")
}

set_field_year_quarter_day_cpp <- function(fields, value, precision_fields, precision_value, start) {
  .Call("_clock_set_field_year_quarter_day_cpp", fields, value, precision_fields, precision_value, start, PACKAGE = "clock")
}

set_field_year_quarter_day_last_cpp <- function(fields, precision_fields, start) {
  .Call("_clock_set_field_year_quarter_day_last_cpp", fields, precision_fields, start, PACKAGE = "clock")
}

year_quarter_day_plus_duration_cpp <- function(fields, fields_n, precision_fields, precision_n, start) {
  .Call("_clock_year_quarter_day_plus_duration_cpp", fields, fields_n, precision_fields, precision_n, start, PACKAGE = "clock")
}

as_sys_time_year_quarter_day_cpp <- function(fields, precision_string, start) {
  .Call("_clock_as_sys_time_year_quarter_day_cpp", fields, precision_string, start, PACKAGE = "clock")
}

as_year_quarter_day_from_sys_time_cpp <- function(fields, precision_string, start) {
  .Call("_clock_as_year_quarter_day_from_sys_time_cpp", fields, precision_string, start, PACKAGE = "clock")
}

year_quarter_day_minus_year_quarter_day_cpp <- function(x, y, precision_string, start) {
  .Call("_clock_year_quarter_day_minus_year_quarter_day_cpp", x, y, precision_string, start, PACKAGE = "clock")
}

sys_now_cpp <- function() {
  .Call("_clock_sys_now_cpp", PACKAGE = "clock")
}

zone_standardize <- function(zone) {
  .Call("_clock_zone_standardize", zone, PACKAGE = "clock")
}

zone_is_valid <- function(zone) {
  .Call("_clock_zone_is_valid", zone, PACKAGE = "clock")
}

zone_current <- function() {
  .Call("_clock_zone_current", PACKAGE = "clock")
}

get_naive_time_cpp <- function(fields, precision_string, zone) {
  .Call("_clock_get_naive_time_cpp", fields, precision_string, zone, PACKAGE = "clock")
}

as_zoned_sys_time_from_naive_time_cpp <- function(fields, precision_string, zone, nonexistent, ambiguous) {
  .Call("_clock_as_zoned_sys_time_from_naive_time_cpp", fields, precision_string, zone, nonexistent, ambiguous, PACKAGE = "clock")
}

to_sys_duration_fields_from_sys_seconds_cpp <- function(seconds) {
  .Call("_clock_to_sys_duration_fields_from_sys_seconds_cpp", seconds, PACKAGE = "clock")
}

to_sys_seconds_from_sys_duration_fields_cpp <- function(fields) {
  .Call("_clock_to_sys_seconds_from_sys_duration_fields_cpp", fields, PACKAGE = "clock")
}

get_offset_cpp <- function(fields, precision_string, zone) {
  .Call("_clock_get_offset_cpp", fields, precision_string, zone, PACKAGE = "clock")
}
