# Generated by cpp11: do not edit by hand

adjust_zone_retain_clock_cpp <- function(x, zone, dst_nonexistent, dst_ambiguous) {
  .Call("_civil_adjust_zone_retain_clock_cpp", x, zone, dst_nonexistent, dst_ambiguous, PACKAGE = "civil")
}

adjust_zoned_cpp <- function(x, value, day_nonexistent, dst_nonexistent, dst_ambiguous, size, adjuster) {
  .Call("_civil_adjust_zoned_cpp", x, value, day_nonexistent, dst_nonexistent, dst_ambiguous, size, adjuster, PACKAGE = "civil")
}

adjust_local_cpp <- function(x, value, size, adjuster) {
  .Call("_civil_adjust_local_cpp", x, value, size, adjuster, PACKAGE = "civil")
}

add_period_to_zoned_cpp <- function(x, n, day_nonexistent, dst_nonexistent, dst_ambiguous, size, unit) {
  .Call("_civil_add_period_to_zoned_cpp", x, n, day_nonexistent, dst_nonexistent, dst_ambiguous, size, unit, PACKAGE = "civil")
}

add_duration_to_zoned_cpp <- function(x, n, size, unit) {
  .Call("_civil_add_duration_to_zoned_cpp", x, n, size, unit, PACKAGE = "civil")
}

add_period_to_local_cpp <- function(x, n, day_nonexistent, size, unit) {
  .Call("_civil_add_period_to_local_cpp", x, n, day_nonexistent, size, unit, PACKAGE = "civil")
}

civil_init <- function() {
  .Call("_civil_civil_init", PACKAGE = "civil")
}

civil_set_install <- function(path) {
  invisible(.Call("_civil_civil_set_install", path, PACKAGE = "civil"))
}

convert_seconds_to_days_and_time_of_day_cpp <- function(seconds, zone) {
  .Call("_civil_convert_seconds_to_days_and_time_of_day_cpp", seconds, zone, PACKAGE = "civil")
}

convert_days_and_time_of_day_to_seconds_cpp <- function(days, time_of_day, zone, dst_nonexistent, dst_ambiguous) {
  .Call("_civil_convert_days_and_time_of_day_to_seconds_cpp", days, time_of_day, zone, dst_nonexistent, dst_ambiguous, PACKAGE = "civil")
}

convert_days_to_year_month_day_cpp <- function(days) {
  .Call("_civil_convert_days_to_year_month_day_cpp", days, PACKAGE = "civil")
}

convert_year_month_day_to_days_cpp <- function(year, month, day, day_nonexistent) {
  .Call("_civil_convert_year_month_day_to_days_cpp", year, month, day, day_nonexistent, PACKAGE = "civil")
}

convert_time_of_day_to_hour_minute_second_cpp <- function(time_of_day) {
  .Call("_civil_convert_time_of_day_to_hour_minute_second_cpp", time_of_day, PACKAGE = "civil")
}

convert_hour_minute_second_to_time_of_day_cpp <- function(hour, minute, second) {
  .Call("_civil_convert_hour_minute_second_to_time_of_day_cpp", hour, minute, second, PACKAGE = "civil")
}

zone_standardize <- function(zone) {
  .Call("_civil_zone_standardize", zone, PACKAGE = "civil")
}

zone_is_valid <- function(zone) {
  .Call("_civil_zone_is_valid", zone, PACKAGE = "civil")
}
