# Generated by cpp11: do not edit by hand

adjust_zone_retain_clock_cpp <- function(x, zone, dst_nonexistent, dst_ambiguous) {
  .Call("_civil_adjust_zone_retain_clock_cpp", x, zone, dst_nonexistent, dst_ambiguous, PACKAGE = "civil")
}

adjust_zoned_cpp <- function(x, value, day_nonexistent, dst_nonexistent, dst_ambiguous, size, adjuster) {
  .Call("_civil_adjust_zoned_cpp", x, value, day_nonexistent, dst_nonexistent, dst_ambiguous, size, adjuster, PACKAGE = "civil")
}

adjust_local_cpp <- function(x, value, day_nonexistent, size, adjuster) {
  .Call("_civil_adjust_local_cpp", x, value, day_nonexistent, size, adjuster, PACKAGE = "civil")
}

add_period_to_zoned_cpp <- function(x, n, day_nonexistent, dst_nonexistent, dst_ambiguous, size, unit) {
  .Call("_civil_add_period_to_zoned_cpp", x, n, day_nonexistent, dst_nonexistent, dst_ambiguous, size, unit, PACKAGE = "civil")
}

add_duration_to_zoned_cpp <- function(x, n, size, unit) {
  .Call("_civil_add_duration_to_zoned_cpp", x, n, size, unit, PACKAGE = "civil")
}

add_period_to_local_cpp <- function(x, n, day_nonexistent, size, unit) {
  .Call("_civil_add_period_to_local_cpp", x, n, day_nonexistent, size, unit, PACKAGE = "civil")
}

civil_init <- function() {
  .Call("_civil_civil_init", PACKAGE = "civil")
}

civil_set_install <- function(path) {
  invisible(.Call("_civil_civil_set_install", path, PACKAGE = "civil"))
}

localize_posixct_cpp <- function(x) {
  .Call("_civil_localize_posixct_cpp", x, PACKAGE = "civil")
}

unlocalize_cpp <- function(x, zone, dst_nonexistent, dst_ambiguous) {
  .Call("_civil_unlocalize_cpp", x, zone, dst_nonexistent, dst_ambiguous, PACKAGE = "civil")
}

zone_standardize <- function(zone) {
  .Call("_civil_zone_standardize", zone, PACKAGE = "civil")
}

zone_is_valid <- function(zone) {
  .Call("_civil_zone_is_valid", zone, PACKAGE = "civil")
}
