new_civil_rcrd <- function(fields, ..., names = NULL, class = NULL) {
  if (length(fields) == 0L) {
    abort("`fields` must be a list of length 1 or greater.")
  }

  size <- length(fields[[1]])
  validate_names(names, size)

  new_rcrd(
    fields = fields,
    ...,
    `civil_rcrd:::names` = names,
    class = c(class, "civil_rcrd")
  )
}

is_civil_rcrd <- function(x) {
  inherits(x, "civil_rcrd")
}

# ------------------------------------------------------------------------------

#' @export
names.civil_rcrd <- function(x) {
  attr(x, "civil_rcrd:::names", exact = TRUE)
}

#' @export
`names<-.civil_rcrd` <- function(x, value) {
  attrib <- attributes(x)

  # Remove names
  if (is.null(value)) {
    attrib[["civil_rcrd:::names"]] <- NULL
    attributes(x) <- attrib

    return(x)
  }

  size <- vec_size(x)
  value <- as_names(value, size)

  attrib[["civil_rcrd:::names"]] <- value
  attributes(x) <- attrib

  x
}

as_names <- function(x, size) {
  x <- unstructure(x)

  if (!is_character(x)) {
    x <- as.character(x)
  }

  validate_names(x, size)

  x
}

validate_names <- function(names, size) {
  if (is_null(names)) {
    return(invisible(names))
  }

  if (!is_character(names)) {
    abort("Names must be a character vector.")
  }

  if (length(names) != size) {
    abort(paste0("Names must have length ", size, " not ", length(names), "."))
  }

  if (any(is.na(names))) {
    abort("Names cannot be `NA`.")
  }

  invisible(names)
}

# ------------------------------------------------------------------------------

# - `[.vctrs_rcrd` accidentally allows subsetting fields through `...`
#   https://github.com/r-lib/vctrs/issues/1295

#' @export
`[.civil_rcrd` <- function(x, i) {
  i <- maybe_missing(i, default = TRUE)
  vec_slice(x, i)
}

# - `[[.vctrs_rcrd` doesn't drop names because names aren't supported for rcrds
# - `[[.vctrs_rcrd` allows selections of size >1
#   https://github.com/r-lib/vctrs/issues/1294

#' @export
`[[.civil_rcrd` <- function(x, i) {
  size <- vec_size(x)
  names <- names(x)

  i <- vec_as_location2(i, n = size, names = names, arg = "i")

  # Unname - `[[` never returns input with names
  x <- unname(x)

  vec_slice(x, i)
}

# ------------------------------------------------------------------------------

# - Each subclass implements a `format()` method
# - Unlike vctrs, don't use `print(quote = FALSE)` since we want to match base R

#' @export
obj_print_data.civil_rcrd <- function(x, ...) {
  obj_print_data_civil_rcrd(x)
}

obj_print_data_civil_rcrd <- function(x, format = NULL) {
  if (vec_size(x) == 0L) {
    return(invisible(x))
  }

  if (is.null(format)) {
    out <- format(x)
  } else {
    out <- format(x, format = format)
  }

  print(out)
  invisible(x)
}

# @export - lazy in .onLoad()
pillar_shaft.civil_rcrd <- function(x, ...) {
  pillar::new_pillar_shaft_simple(format(x), align = "left")
}

# ------------------------------------------------------------------------------

proxy_civil_rcrd <- function(x) {
  out <- unclass(x)
  out[["civil_rcrd:::names"]] <- names(x)
  out <- new_data_frame(out)
  out
}

proxy_equal_civil_rcrd <- function(x) {
  out <- unclass(x)
  out <- new_data_frame(out)
  out
}

restore_civil_rcrd_fields <- function(x) {
  x[["civil_rcrd:::names"]] <- NULL
  names <- names(x)
  x <- unstructure(x)
  names(x) <- names
  x
}

restore_civil_rcrd_names <- function(x) {
  names <- x[["civil_rcrd:::names"]]
  names <- repair_na_names(names)
  names
}

# Patch required to repair `NA` names generated by `vec_slice()`
# and `chr_slice()`. Same idea as the C level `repair_na_names()` in
# https://github.com/r-lib/vctrs/blob/7f5134f3b0ae747407321c57451f2eee60722ce3/src/slice.c#L265
# Should go away if we get names support in a vctrs rcrd
repair_na_names <- function(names) {
  na <- is.na(names)

  if (any(na)) {
    names[na] <- ""
  }

  names
}


